#
# Copyright (C) 2017 Brady Miller <brady.g.miller@gmail.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# php:7.1-fpm-alpine docker build that supports ssh
#
FROM php:7.1-fpm-alpine

# Add support for ssh
RUN apk add --no-cache openssh

