REPLACE INTO globals VALUES ('portal_onsite_enable'  , 0, '1');
REPLACE INTO globals VALUES ('portal_onsite_two_enable'  , 0, '1');
REPLACE INTO globals VALUES ('gbl_portal_cms_enable'  , 0, '1');
REPLACE INTO globals VALUES ('gbl_portal_cms_address' , 0, 'http://demo.open-emr.org:2104/wordpress');
REPLACE INTO globals VALUES ('gbl_portal_cms_username', 0, 'cmsportal');
REPLACE INTO globals VALUES ('gbl_portal_cms_password', 0, 'cmsportal');
REPLACE INTO globals VALUES ('rest_api', 0, '1');
REPLACE INTO globals VALUES ('rest_fhir_api', 0, '1');
REPLACE INTO globals VALUES ('rest_portal_api', 0, '1');
REPLACE INTO globals VALUES ('rest_portal_fhir_api', 0, '1');
REPLACE INTO globals VALUES ('oauth_password_grant', 0, '3');
REPLACE INTO globals VALUES ('rest_system_scopes_api', 0, '1');